### ISSUE TITLE
Reporte de Práctica - Contrato S4GPS

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-entrevista-sistemhuerto#1]
Aquí se anexan los reportes de práctica...

**Comment by Yabin-2021** [comment]
Rúbrica para evaluar
[Rúbrica reporte de practica de Contrato.docx](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-entrevista-sistemhuerto/files/10159084/Rubrica.reporte.de.practica.de.Contrato.docx)

Reporte de práctica:
[S4GPS 02 - Práctica Contrato.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-entrevista-sistemhuerto/files/10159085/S4GPS.02.-.Practica.Contrato.pdf)

**Comment by IsaHuerta23** [comment]
Portada: 25.
Procedimiento: 25.
Figuras, ilustraciones y fotografías: 25.
Resultados y conclusiones: 25.
Total: 100. 
Calificación: 50.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
